// Code generated by protoc-gen-retag. DO NOT EDIT.
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: example/example.proto

package example

import (
	_ "github.com/pubgo/protoc-gen-retag/pkg/retag"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Example struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WithNewTags     string                 `protobuf:"bytes,1,opt,name=with_new_tags,json=withNewTags,proto3" json:"with_new_tags,omitempty" graphql:"withNewTags,optional"`
	WithNewMultiple string                 `protobuf:"bytes,2,opt,name=with_new_multiple,json=withNewMultiple,proto3" json:"with_new_multiple,omitempty" graphql:"withNewTags,optional" xml:"multi,omitempty"`
	ReplaceDefault  string                 `protobuf:"bytes,3,opt,name=replace_default,json=replaceDefault,proto3" json:"replacePrevious111,omitempty"`
	// Types that are valid to be assigned to OneOf:
	//
	//	*Example_A
	//	*Example_BJk
	OneOf         isExample_OneOf `protobuf_oneof:"one_of" graphql:"withNewTags,optional"`
	ID            *string         `protobuf:"bytes,4,opt,name=ID,proto3,oneof" json:"ID,omitempty"`
	Mm            *SecondMessage  `protobuf:"bytes,7,opt,name=mm,proto3" json:"mm,omitempty"`
	Mm2           *SecondMessage  `protobuf:"bytes,8,opt,name=mm2,proto3,oneof" json:"mm2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Example) Reset() {
	*x = Example{}
	mi := &file_example_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Example) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Example) ProtoMessage() {}

func (x *Example) ProtoReflect() protoreflect.Message {
	mi := &file_example_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Example.ProtoReflect.Descriptor instead.
func (*Example) Descriptor() ([]byte, []int) {
	return file_example_example_proto_rawDescGZIP(), []int{0}
}

func (x *Example) GetWithNewTags() string {
	if x != nil {
		return x.WithNewTags
	}
	return ""
}

func (x *Example) GetWithNewMultiple() string {
	if x != nil {
		return x.WithNewMultiple
	}
	return ""
}

func (x *Example) GetReplaceDefault() string {
	if x != nil {
		return x.ReplaceDefault
	}
	return ""
}

func (x *Example) GetOneOf() isExample_OneOf {
	if x != nil {
		return x.OneOf
	}
	return nil
}

func (x *Example) GetA() string {
	if x != nil {
		if x, ok := x.OneOf.(*Example_A); ok {
			return x.A
		}
	}
	return ""
}

func (x *Example) GetBJk() int32 {
	if x != nil {
		if x, ok := x.OneOf.(*Example_BJk); ok {
			return x.BJk
		}
	}
	return 0
}

func (x *Example) GetID() string {
	if x != nil && x.ID != nil {
		return *x.ID
	}
	return ""
}

func (x *Example) GetMm() *SecondMessage {
	if x != nil {
		return x.Mm
	}
	return nil
}

func (x *Example) GetMm2() *SecondMessage {
	if x != nil {
		return x.Mm2
	}
	return nil
}

type isExample_OneOf interface {
	isExample_OneOf()
}

type Example_A struct {
	A string `protobuf:"bytes,5,opt,name=a,proto3,oneof" json:"A111"`
}

type Example_BJk struct {
	BJk int32 `protobuf:"varint,6,opt,name=b_jk,json=bJk,proto3,oneof" json:"b_Jk1111"`
}

func (*Example_A) isExample_OneOf() {}

func (*Example_BJk) isExample_OneOf() {}

type SecondMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WithNewTags     string                 `protobuf:"bytes,1,opt,name=with_new_tags,json=withNewTags,proto3" json:"with_new_tags,omitempty" graphql:"withNewTags,optional"`
	WithNewMultiple string                 `protobuf:"bytes,2,opt,name=with_new_multiple,json=withNewMultiple,proto3" json:"with_new_multiple,omitempty" graphql:"withNewTags,optional" xml:"multi,omitempty"`
	ReplaceDefault  string                 `protobuf:"bytes,3,opt,name=replace_default,json=replaceDefault,proto3" json:"replacePrevious1111,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SecondMessage) Reset() {
	*x = SecondMessage{}
	mi := &file_example_example_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecondMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecondMessage) ProtoMessage() {}

func (x *SecondMessage) ProtoReflect() protoreflect.Message {
	mi := &file_example_example_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecondMessage.ProtoReflect.Descriptor instead.
func (*SecondMessage) Descriptor() ([]byte, []int) {
	return file_example_example_proto_rawDescGZIP(), []int{1}
}

func (x *SecondMessage) GetWithNewTags() string {
	if x != nil {
		return x.WithNewTags
	}
	return ""
}

func (x *SecondMessage) GetWithNewMultiple() string {
	if x != nil {
		return x.WithNewMultiple
	}
	return ""
}

func (x *SecondMessage) GetReplaceDefault() string {
	if x != nil {
		return x.ReplaceDefault
	}
	return ""
}

type ThirdExample struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	InnerExample  *ThirdExample_InnerExample `protobuf:"bytes,1,opt,name=inner_example,json=innerExample,proto3" json:"inner1111,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThirdExample) Reset() {
	*x = ThirdExample{}
	mi := &file_example_example_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThirdExample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThirdExample) ProtoMessage() {}

func (x *ThirdExample) ProtoReflect() protoreflect.Message {
	mi := &file_example_example_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThirdExample.ProtoReflect.Descriptor instead.
func (*ThirdExample) Descriptor() ([]byte, []int) {
	return file_example_example_proto_rawDescGZIP(), []int{2}
}

func (x *ThirdExample) GetInnerExample() *ThirdExample_InnerExample {
	if x != nil {
		return x.InnerExample
	}
	return nil
}

type ThirdExample_InnerExample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"yes222,omitempty"`
	Yes           int32                  `protobuf:"varint,2,opt,name=yes,proto3" json:"id111,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThirdExample_InnerExample) Reset() {
	*x = ThirdExample_InnerExample{}
	mi := &file_example_example_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThirdExample_InnerExample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThirdExample_InnerExample) ProtoMessage() {}

func (x *ThirdExample_InnerExample) ProtoReflect() protoreflect.Message {
	mi := &file_example_example_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThirdExample_InnerExample.ProtoReflect.Descriptor instead.
func (*ThirdExample_InnerExample) Descriptor() ([]byte, []int) {
	return file_example_example_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ThirdExample_InnerExample) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ThirdExample_InnerExample) GetYes() int32 {
	if x != nil {
		return x.Yes
	}
	return 0
}

var File_example_example_proto protoreflect.FileDescriptor

const file_example_example_proto_rawDesc = "" +
	"\n" +
	"\x15example/example.proto\x12\aexample\x1a\x17proto/retag/retag.proto\"\xfd\x03\n" +
	"\aExample\x12G\n" +
	"\rwith_new_tags\x18\x01 \x01(\tB#\x82\xea0\x1f\n" +
	"\agraphql\x12\x14withNewTags,optionalR\vwithNewTags\x12i\n" +
	"\x11with_new_multiple\x18\x02 \x01(\tB=\x82\xea0\x1f\n" +
	"\agraphql\x12\x14withNewTags,optional\x82\xea0\x16\n" +
	"\x03xml\x12\x0fmulti,omitemptyR\x0fwithNewMultiple\x12G\n" +
	"\x0freplace_default\x18\x03 \x01(\tB\x1e\x82\xea0\x1a\n" +
	"\x04json\x12\x12replacePrevious111R\x0ereplaceDefault\x12 \n" +
	"\x01a\x18\x05 \x01(\tB\x10\x82\xea0\f\n" +
	"\x04json\x12\x04A111H\x00R\x01a\x12)\n" +
	"\x04b_jk\x18\x06 \x01(\x05B\x14\x82\xea0\x10\n" +
	"\x04json\x12\bb_Jk1111H\x00R\x03bJk\x12\x13\n" +
	"\x02ID\x18\x04 \x01(\tH\x01R\x02ID\x88\x01\x01\x12&\n" +
	"\x02mm\x18\a \x01(\v2\x16.example.SecondMessageR\x02mm\x12-\n" +
	"\x03mm2\x18\b \x01(\v2\x16.example.SecondMessageH\x02R\x03mm2\x88\x01\x01B-\n" +
	"\x06one_of\x12#\x82\xea0\x1f\n" +
	"\agraphql\x12\x14withNewTags,optionalB\x05\n" +
	"\x03_IDB\x06\n" +
	"\x04_mm2\"\x8d\x02\n" +
	"\rSecondMessage\x12G\n" +
	"\rwith_new_tags\x18\x01 \x01(\tB#\x82\xea0\x1f\n" +
	"\agraphql\x12\x14withNewTags,optionalR\vwithNewTags\x12i\n" +
	"\x11with_new_multiple\x18\x02 \x01(\tB=\x82\xea0\x1f\n" +
	"\agraphql\x12\x14withNewTags,optional\x82\xea0\x16\n" +
	"\x03xml\x12\x0fmulti,omitemptyR\x0fwithNewMultiple\x12H\n" +
	"\x0freplace_default\x18\x03 \x01(\tB\x1f\x82\xea0\x1b\n" +
	"\x04json\x12\x13replacePrevious1111R\x0ereplaceDefault\"\xd9\x01\n" +
	"\fThirdExample\x12^\n" +
	"\rinner_example\x18\x01 \x01(\v2\".example.ThirdExample.InnerExampleB\x15\x82\xea0\x11\n" +
	"\x04json\x12\tinner1111R\finnerExample\x1ai\n" +
	"\fInnerExample\x124\n" +
	"\x02id\x18\x01 \x01(\tB$\x82\xea0\x0e\n" +
	"\x04json\x12\x06yes111\x82\xea0\x0e\n" +
	"\x04json\x12\x06yes222R\x02id\x12#\n" +
	"\x03yes\x18\x02 \x01(\x05B\x11\x82\xea0\r\n" +
	"\x04json\x12\x05id111R\x03yesB7Z5github.com/pubgo/protoc-gen-retag/pkg/example;exampleb\x06proto3"

var (
	file_example_example_proto_rawDescOnce sync.Once
	file_example_example_proto_rawDescData []byte
)

func file_example_example_proto_rawDescGZIP() []byte {
	file_example_example_proto_rawDescOnce.Do(func() {
		file_example_example_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_example_example_proto_rawDesc), len(file_example_example_proto_rawDesc)))
	})
	return file_example_example_proto_rawDescData
}

var file_example_example_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_example_example_proto_goTypes = []any{
	(*Example)(nil),                   // 0: example.Example
	(*SecondMessage)(nil),             // 1: example.SecondMessage
	(*ThirdExample)(nil),              // 2: example.ThirdExample
	(*ThirdExample_InnerExample)(nil), // 3: example.ThirdExample.InnerExample
}
var file_example_example_proto_depIdxs = []int32{
	1, // 0: example.Example.mm:type_name -> example.SecondMessage
	1, // 1: example.Example.mm2:type_name -> example.SecondMessage
	3, // 2: example.ThirdExample.inner_example:type_name -> example.ThirdExample.InnerExample
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_example_example_proto_init() }
func file_example_example_proto_init() {
	if File_example_example_proto != nil {
		return
	}
	file_example_example_proto_msgTypes[0].OneofWrappers = []any{
		(*Example_A)(nil),
		(*Example_BJk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_example_proto_rawDesc), len(file_example_example_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_example_example_proto_goTypes,
		DependencyIndexes: file_example_example_proto_depIdxs,
		MessageInfos:      file_example_example_proto_msgTypes,
	}.Build()
	File_example_example_proto = out.File
	file_example_example_proto_goTypes = nil
	file_example_example_proto_depIdxs = nil
}
